<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>基于SAE网站监控服务(测试版)</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>基于SAE网站监控服务(测试版)</a></h1>
		<form id="form_367143" class="appnitro"  method="post" action="index.php">
					<div class="form_description">
			<h2>基于SAE网站监控服务(测试版)</h2>
			<p>目前此服务处于测试期间,因此不保证服务以后是否会变更,虽然SAE的稳定性很好,但是价钱不好,所以有限制名额的打算,请斟酌后选择使用!</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">网址(HTTP协议) </label>
		<div>
			<input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_1"><small>暂时不支持HTTPS,FTP,FTPS等协议,以后会完善的!只需要填写后面部分,例如www.lijingquan.net,程序还没有完善,目前只要绑定了就不能删除!</small></p> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">监控频率 </label>
		<div>
		<select class="element select medium" id="element_4" name="element_4"> 
<option value="1" selected="selected">5分钟/次</option>

		</select>
		</div><p class="guidelines" id="guide_4"><small>测试期间只提供5分钟一次的检测频率,实际上要实现1秒检测一次不是技术问题,只是资源问题,如果有资源提供者愿意,或者代码优化,将会得到更高的监控密度!</small></p> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">邮箱地址 </label>
		<div>
			<input id="element_3" name="element_3" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_3"><small>使用Gmail效果最好,使用手机邮箱能收到短信通知!不过,我有打算以后开通微博通知版,毕竟SAE的邮件限制比较多!而且CPU消耗也大!</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">验证信息 </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>请填写目前你网站的IP地址,此IP地址只是充当验证码功效!并不代表以后你的网站不能更改IP地址!</small></p> 
		</li>
			
					<li class="buttons">
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="OK" />
		</li>
			</ul>
		</form>	
		<div id="footer">
                  Generated by <a href="http://www.phpform.org">pForm</a> & Code by <a href="http://www.lijingquan.net">Tater</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>

<?
if($_POST[submit] == 'OK'){
if ($_POST[element_2] == gethostbyname($_POST[element_1])){
preg_match("/^([a-zA-Z0-9_-])+@(?:gmail.com|139.com|189.cn|wo.com.cn)/",$_POST[element_3],$m);
  if ($m[0] == NULL){
  echo '邮箱地址非法!（反机器人系统）';
  }else
  {
    $kv = new SaeKV();
    $ret = $kv->init();
    $kv->set('web_'.$_POST[element_1], $_POST[element_1]);
    $kv->set('mail_http://'.$_POST[element_1], $_POST[element_3]);  echo '邮箱地址合法!';
  }
}else{
  echo '验证信息处应该填写你网站的IP地址,请再次填写!（反机器人系统）';}
}
?>
